---
title: "Lab 5"
author: "Steph Bossert"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) 
library(dsbox) 
View(dennys)
```

```{r}
dn<- dennys
```

###Question 1
###3 Denny's in Alaska

```{r 1}
dn_ak <- dn %>%
  filter(state == "AK")
nrow(dn_ak)
```

###Question 2
###Answer: 2 Laquintas in AK
```{r 2}
view(laquinta)
lq<- laquinta
lq_ak <- lq %>%
  filter(state == "AK")
nrow(lq_ak)
```
###Question 3
###Answer: 6 pairings
```{r 3}
dn_lq_ak <- full_join(dn_ak, lq_ak, by = "state")
view(dn_lq_ak)
```
###Question 4
###Answer:  6 Obersvations, 11 variables (Address, city, state, zip, lat, long) x2

###Question 5: Mutate

```{r 6}
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  R = 6371 # Earth mean radius in km
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  
  return( round(d,round) ) # distance in km
}
```

```{r}
dn_lq_ak <- dn_lq_ak %>% mutate(distance = haversine(longitude.x, latitude.x,
            longitude.y, latitude.y, round = 3))
view(dn_lq_ak)
```


###Question 7
```{r 7}
dn_lq_ak_mindist <- dn_lq_ak %>%
  group_by(address.x) %>%
  summarise(closest = min(distance))
view(dn_lq_ak_mindist)
```
###Question 8
```{r}
ggplot(dn_lq_ak, mapping = aes(x = longitude.x, y = latitude.x, color = address.x, alpha = .05)) +
  geom_point()
```
###North Carolina Data
```{r NC}
dn_nc <- dn %>%
  filter(state == "NC")
nrow(dn_nc)

view(laquinta)
lq<- laquinta
lq_nc <- lq %>%
  filter(state == "NC")
nrow(lq_nc)
dn_lq_nc <- full_join(dn_nc, lq_nc, by = "state")
view(dn_lq_nc)
dn_lq_nc <- dn_lq_nc %>% mutate(distance = haversine(longitude.x, latitude.x,
            longitude.y, latitude.y, round = 3))
dn_lq_nc_mindist <- dn_lq_nc %>%
  group_by(address.x) %>%
  summarise(closest = min(distance))
view(dn_lq_nc_mindist)
 ggplot(dn_lq_ak, mapping = aes(x = longitude.x, y = latitude.x, color = address.x, alpha = .05)) +
  geom_point()
```


```{r TX}
dn_tx <- dn %>%
  filter(state == "TX")
nrow(dn_tx)

view(laquinta)
lq<- laquinta
lq_tx <- lq %>%
  filter(state == "TX")
nrow(lq_tx)
dn_lq_tx <- full_join(dn_tx, lq_tx, by = "state")
view(dn_lq_tx)
dn_lq_tx <- dn_lq_tx %>% mutate(distance = haversine(longitude.x, latitude.x,
            longitude.y, latitude.y, round = 3))
dn_lq_tx_mindist <- dn_lq_tx %>%
  group_by(address.x) %>%
  summarise(closest = min(distance))
view(dn_lq_tx_mindist)
ggplot(dn_lq_tx, mapping = aes(x = longitude.x, y = latitude.x, color = address.x, alpha = .05)) +
  geom_point()
```

```{r NY}
dn_ny <- dn %>%
  filter(state == "NY")
nrow(dn_ny)

view(laquinta)
lq<- laquinta
lq_ny <- lq %>%
  filter(state == "NY")
nrow(lq_ny)
dn_lq_ny <- full_join(dn_ny, lq_ny, by = "state")
view(dn_lq_ny)
dn_lq_ny <- dn_lq_ny %>% mutate(distance = haversine(longitude.x, latitude.x,
            longitude.y, latitude.y, round = 3))
dn_lq_ny_mindist <- dn_lq_ny %>%
  group_by(address.x) %>%
  summarise(closest = min(distance))
view(dn_lq_ny_mindist)

ggplot(dn_lq_ny, mapping = aes(x = longitude.x, y = latitude.x, color = address.x, alpha = .05)) +
  geom_point()
```




